update dependencies rust-1.46.0
blue-yonder/di-csv2xml pull request #38
Opened 2020-10-13 08:48 UTC by marco-neumann-by

2020-10-14 06:58 UTC, steffen-schroeder-by approved these changes

2020-10-15 14:21 UTC, pacman82 requested changes

2020-10-15 14:21 UTC, pacman82 commented on Cargo.toml
>  quick-xml = { git = "https://github.com/pacman82/quick-xml.git" }
This has been already changed on master, to the new upstream version. I suggest re-basing the PR.

2020-10-25 18:30 UTC, pacman82 approved these changes

2020-10-25 18:46 UTC, pacman82 commented
Closing this, as dependencies are already up to date on master

2020-10-25 18:46 UTC, closed without merging